#!/bin/bash
# Use this script to re-create configure. Requires the following auto-tools,
# autoconf        >= 2.59
# automake        >= 1.9
# libtool         >= 1.4
glibtoolize -f 2>/dev/null || libtoolize -f
if aclocal -I config && autoheader && automake --foreign --add-missing --copy && autoconf 
then
        cd libmonit || exit 1;
        ./bootstrap || exit 1;
        echo "Success bootstrapping Monit" 
        exit 0;
fi
echo "Failed bootstrapping Monit"
exit 1;
