#!/bin/sh
# Use this script to re-create configure. Requires the following auto-tools,
# autoconf        >= 2.59
# automake        >= 1.9
# libtool         >= 1.4
#!/bin/bash
libtoolize -f 2>/dev/null || glibtoolize -f
if aclocal -I config && autoheader && automake --foreign --add-missing --copy && autoconf 
then
        echo "Success bootstrapping libmonit"
else
        echo "Failed bootstrapping libmonit"
        exit 1;
fi
exit 0;
